# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinchwork < Formula
  desc "CLI for the Pinchwork agent-to-agent task marketplace"
  homepage "https://pinchwork.dev"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anneschuth/pinchwork/releases/download/v0.3.0/pinchwork-0.3.0-darwin-amd64.tar.gz"
      sha256 "ca416372b9fe4dcfb379c7d289c3f0791c5dc18072fc4d581b3d458b57b738f9"

      def install
        bin.install "pinchwork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anneschuth/pinchwork/releases/download/v0.3.0/pinchwork-0.3.0-darwin-arm64.tar.gz"
      sha256 "86b6eb16398b8d0bed5fa3acb2a9ec0e5c8ff3d8eb8681100451face36efc34d"

      def install
        bin.install "pinchwork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anneschuth/pinchwork/releases/download/v0.3.0/pinchwork-0.3.0-linux-amd64.tar.gz"
      sha256 "3e1fea5d4487e341f9051285096dd924562f4cad8c6ca4a844baf6c3271a3e57"
      def install
        bin.install "pinchwork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anneschuth/pinchwork/releases/download/v0.3.0/pinchwork-0.3.0-linux-arm64.tar.gz"
      sha256 "7ae8f6697a0d5ea576fae85b1f0d8cecea50a5d2428e0d0f531566900a579f51"
      def install
        bin.install "pinchwork"
      end
    end
  end

  test do
    system "#{bin}/pinchwork", "--version"
  end
end
